Refs #62: common.channels with inmemory layer and redispubsub layer
DmitryBurnaev/starlette-web pull request #105
Opened 2023-03-08 14:58 UTC by dolamroth

2023-03-12 18:28 UTC, DmitryBurnaev requested changes

2023-03-12 20:00 UTC, dolamroth commented on starlette_web/common/channels/layers/local_memory.py
> +        assert self._receive_stream
поменял

2023-03-12 20:00 UTC, dolamroth commented on starlette_web/contrib/postgres/channel_layers.py
> +            ), "Message byte-length must be at most 8000 symbols"
поменял

2023-03-12 20:00 UTC, dolamroth commented on starlette_web/tests/views/websocket.py
> +                return
добавил

2023-03-12 20:01 UTC, dolamroth commented on starlette_web/contrib/postgres/channel_layers.py
> +    def __init__(self, **options) -> None:
готово

2023-03-12 20:02 UTC, dolamroth commented on starlette_web/contrib/redis/channel_layers.py
> +    serializer_class: Type[BaseSerializer] = PickleSerializer
нативно байткод, не надо энкодить-декодить, плюс юзер может отнаследовать класс и поменять сериализатор

2023-03-13 08:03 UTC, DmitryBurnaev approved these changes

2023-03-13 08:03 UTC, merged