Refactor step
DmitryBurnaev/starlette-web pull request #15
Opened 2022-05-05 08:42 UTC by dolamroth

Main aim of this step is to isolate different modules, so as to be able to refactor them further separately.

- Split common.utils to several files, corresponding to their purpose. Some of the utils are moved to common.http, and string utils are removed;
- get_app is substitited with a class BaseStarletteApplication, that a user may inherit from. BaseStarletteApplication provides a full set of methods to instantiate application;
- Exception handlers are switched to class-based;
- Redis module is moved to contrib;
- Added generic serializer classes. Redis client now uses them to serialize and deserialize data. Tests for serializers also added;
- Auth module is moved to contrib;
- In general, "common" module now only has app-agnostic code;
- Many TODOs added for further refactoring

2022-05-06 13:54 UTC, DmitryBurnaev requested changes

2022-05-06 13:54 UTC, DmitryBurnaev commented on starlette_web/common/utils/logging.py
> +def log_message(exc, error_data, level=logging.ERROR):
хм. а стоит его тут размещать, если использоваться вроде должен только в exception хендлере?

2022-05-06 13:54 UTC, DmitryBurnaev commented on starlette_web/common/utils/serializers.py
> +        return json.dumps(content)
может тут стоит использовать StarletteJSONEncoder ?

2022-05-06 13:54 UTC, DmitryBurnaev commented on starlette_web/common/utils/serializers.py
> +        return self.__class__ == other.__class__
а для чего нам нужно сраванивать инстансы сериалайзера по классам?

2022-05-06 13:54 UTC, DmitryBurnaev commented on starlette_web/common/app.py
> +        # To be reloaded in inherited class
может тогда стоит заставить его переопределять через `raise NotImplementedError`?

2022-05-06 13:54 UTC, DmitryBurnaev commented on starlette_web/common/app.py
> +        # TODO: remove
можешь плиз пояснить: почему нужно имплементировать метод, который потом хочешь удалить?

2022-05-06 13:54 UTC, DmitryBurnaev commented on starlette_web/common/http/requests.py
>      db_session: AsyncSession
по идее инстанс PRequest-а связан с текущей сессией юзера. В моем проекте было удобно опираться на это (ибо логично вроде). Зачем мы убираем session_id? какую проблему это может решить?

2022-05-07 08:59 UTC, dolamroth commented on starlette_web/common/utils/serializers.py
> +        return self.__class__ == other.__class__
Чисто для тестов добавил

2022-05-07 08:59 UTC, dolamroth commented on starlette_web/common/app.py
> +        # To be reloaded in inherited class
Это необязательный метод

2022-05-07 09:00 UTC, dolamroth commented on starlette_web/common/app.py
> +        # TODO: remove
Коммент относится к логированию и сентри.
Имею в виду, что эту логику нужно сделать частной.

2022-05-07 09:02 UTC, dolamroth commented on starlette_web/common/http/requests.py
>      db_session: AsyncSession
Я перенес user_session_id в scope, который в эндпоинтах доступен через self.scope
request.user по-прежнему доступен

Если что-то пропихивать в request, то нужно что-то более общее, как request.auth в DRF

2022-05-07 09:02 UTC, dolamroth commented on starlette_web/common/utils/serializers.py
> +        return json.dumps(content)
Я тоже об этом думал, но тогда будет неоднозначная сериализация-десериализация

2022-05-07 09:37 UTC, dolamroth commented on starlette_web/common/utils/logging.py
> +def log_message(exc, error_data, level=logging.ERROR):
get_logger я бы вообще убрал, а log_message можно и правда перенести в exception handler
Что думаешь?

2022-05-07 11:10 UTC, DmitryBurnaev commented on starlette_web/common/utils/logging.py
> +def log_message(exc, error_data, level=logging.ERROR):
думаю да. давай так и сделаем)

2022-05-07 11:11 UTC, DmitryBurnaev commented on starlette_web/common/utils/serializers.py
> +        return json.dumps(content)
может как опциональный параметр (StarletteJSONEncoder) тогда добавить в метод serialize или как параметр класса?
было бы удобно просто сериализовать данные в респонс не думая о доп.преобразованиях)

2022-05-07 11:12 UTC, DmitryBurnaev commented on starlette_web/common/utils/serializers.py
> +        return self.__class__ == other.__class__
немного странно просто выглядит логика этого метода) я не против вцелом

2022-05-07 11:14 UTC, DmitryBurnaev commented on starlette_web/common/app.py
> +        # To be reloaded in inherited class
тогда в докстринге нужно описать что-то вроде
```python
"""
Extra actions before app's initialization (can be overridden)
"""
```

2022-05-07 11:15 UTC, DmitryBurnaev commented on starlette_web/common/app.py
> +        # TODO: remove
напиши тогда плиз чуть по-подробнее в туду (если не сложно)

2022-05-07 11:15 UTC, DmitryBurnaev commented on starlette_web/common/http/requests.py
>      db_session: AsyncSession
а. я тебя понял) спасибо! тогда я всеми руками за))

2022-05-08 12:50 UTC, dolamroth commented on starlette_web/common/utils/logging.py
> +def log_message(exc, error_data, level=logging.ERROR):
готово

2022-05-08 12:58 UTC, dolamroth commented on starlette_web/common/app.py
> +        # TODO: remove
готово

2022-05-08 12:58 UTC, dolamroth commented on starlette_web/common/app.py
> +        # To be reloaded in inherited class
готово

2022-05-08 12:58 UTC, dolamroth commented on starlette_web/common/utils/serializers.py
> +        return json.dumps(content)
готово

2022-05-08 13:38 UTC, DmitryBurnaev approved these changes

2022-05-08 13:38 UTC, merged