[#10] RedisCache based on aioredis
DmitryBurnaev/starlette-web pull request #19
Opened 2022-05-09 18:01 UTC by dolamroth

2022-05-13 13:56 UTC, DmitryBurnaev requested changes

2022-05-13 13:56 UTC, DmitryBurnaev commented on starlette_web/common/caches/__init__.py
> +# Copy from https://github.com/django/django/blob/main/django/core/cache/__init__.py
давай не будем в `__init__.py` логику писать? код будет вызываться при любом импорте, что вроде не лучший сценарий(( можем лучше создать модуль скажем `commont.caches.cach`, скинуть туда код, а в `__init__.py` заимпортировать.

2022-05-13 13:56 UTC, DmitryBurnaev commented on starlette_web/common/caches/__init__.py
> +caches = CacheHandler()
как думаешь - не лучше будеь сделать синглтоном?

2022-05-13 13:56 UTC, DmitryBurnaev commented on starlette_web/core/settings.py
> +}
редис может использоваться не только для кеша. можем оставить параметры в settings-ах для него?
(я про `REDIS_CON = (REDIS_HOST, REDIS_PORT, REDIS_DB)`)

2022-05-13 13:56 UTC, DmitryBurnaev commented on starlette_web/common/app.py
> +                _ = caches[key]
```python
for conn_name in settings.CACHES:
    _ = caches[key]
```

2022-05-13 13:56 UTC, DmitryBurnaev commented on setup.cfg
> +    aioredis>=2.0.1
лучше ограничивать версию либы сверху (хотя бы до минорной версии)
```
aioredis>2.0.1,<2.1
```

2022-05-13 13:56 UTC, DmitryBurnaev commented on starlette_web/common/caches/base.py
> +    async def async_keys(self, pattern: str) -> List[str]:
`-> list[str]:`

2022-05-13 14:22 UTC, dolamroth commented on starlette_web/core/settings.py
> +}
Нам такое понадобилось делать только в одном проекте, емнип, и там я сделал вот так:
Имхо удобнее -- не надо создавать несколько connection pool'ов

```
    @property
    def redis(self) -> Redis:
        return caches['default'].client.get_client()
```

Но даже если намеренно делать отдельное соединение - это уже частная логика, и её лучше дать на откуп пользователю, нежели помещать в стандартном settings.py (который будет ещё переделываться, но позже)

2022-05-13 14:25 UTC, dolamroth commented on starlette_web/common/caches/base.py
> +    async def async_keys(self, pattern: str) -> List[str]:
У меня просто PyCharm старый, не понимает такой синтаксис))

2022-05-13 14:38 UTC, DmitryBurnaev commented on starlette_web/core/settings.py
> +}
ok) я не против, просто у меня на проекте использовался коннекшн к редису не только для кеша)
но могу у себя потом добавить - без проблем

2022-05-13 14:38 UTC, DmitryBurnaev commented on starlette_web/common/caches/base.py
> +    async def async_keys(self, pattern: str) -> List[str]:
скачай новый) этот синтакс прилетел с 3.10

2022-05-13 14:40 UTC, DmitryBurnaev commented on starlette_web/common/caches/base.py
> +    async def async_keys(self, pattern: str) -> List[str]:
или новый pycharm  - проблема? просто немного грустно, когда не можешь использовать новые штуки из языка только изза того что IDE их не умеет((

2022-05-14 13:15 UTC, DmitryBurnaev approved these changes

2022-05-14 13:15 UTC, merged