Refactor sending emails, move sendgrid code to contrib
DmitryBurnaev/starlette-web pull request #28
Opened 2022-05-21 09:47 UTC by dolamroth

2022-05-21 17:59 UTC, DmitryBurnaev requested changes

2022-05-21 17:59 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +        return self
а зачем мы базовый сендер делаем именно контекстным менеджером? какие мы проблемы этим закрываем?

2022-05-21 17:59 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +        raise NotImplementedError
действительно нужно 2 отдельных метода. выглядит что отправка на 1 получатель это частный случай отправки на несколько. тем более что многие провайдеры позволяют отправлять письма сразу на несколько получателей

2022-05-21 17:59 UTC, DmitryBurnaev commented on starlette_web/common/email/email_manager.py
> +            await sender.send_email(subject, html_content, to_email, from_email=from_email)
в продолжении к предыдущему комменту: я бы оставил 1 метод (если нужно отправить на 1отправителя, можно передать список из 1емейла)

2022-05-21 17:59 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +        self.details = details or ""
странно выглядит этот Exception. если это базовая ошибка при отправке емейлов, то при чем тут request_url?
если он завязан на отправку емейлов через какого-либо провайдера (например Sendgrid), то может унаследовать его от SendRequestError (это упростит реализацию)

2022-05-21 17:59 UTC, DmitryBurnaev commented on starlette_web/contrib/sendgrid/email.py
> +        self.logger = logging.getLogger(__name__)
кажется, логгер лучше вынести на уровень модуля. ему нет смысла быть в инстансе сендера

2022-05-21 17:59 UTC, DmitryBurnaev commented on starlette_web/contrib/sendgrid/email.py
> +            "personalizations": [{"to": [{"email": to_email}], "subject": subject}],
об этом говорил выше. sendgrid позволяет сразу нескольким емейлам делать отправку, просто указав их тут :) думаю можно упростить реализацию этим

2022-05-21 19:22 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +        self.details = details or ""
Я пока что скопировал набор полей из SendRequestError, он там отличается от других BaseApplicationError.

Рейзить здесь SendRequestError считаю неправильным, потому что SendRequestError имеет status_code -- т.е. это ошибка эндпоинта. А эта ошибка может зарейзиться где угодно, например в management-команде.

2022-05-21 19:23 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +        raise NotImplementedError
2 метода сделал как в джанге, оставлю так. На усмотрение пользователя можно определить 1 метод или оба.

2022-05-21 19:23 UTC, dolamroth commented on starlette_web/contrib/sendgrid/email.py
> +            "personalizations": [{"to": [{"email": to_email}], "subject": subject}],
Согласен, не заметил. Определю для этого класса второй метод.

2022-05-21 19:26 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +        return self
EmailManager его использует как контекстный менеджер. А так, чтобы везде было одинаково.

Насчёт целесообразности того, нужно ли где-то специальный метод для открытия-закрытия соединения -- не уверен, сделал на всякий случай. К тому же, в джанге так сделано  https://github.com/django/django/blob/main/django/core/mail/backends/base.py#L44 (кстати, обработку ошибки из `__enter__` тоже перенесу)

2022-05-22 12:27 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +        self.details = details or ""
По итогу request_url нигде не используется, удалил его

2022-05-22 12:29 UTC, dolamroth commented on starlette_web/common/email/email_manager.py
> +            await sender.send_email(subject, html_content, to_email, from_email=from_email)
Переделал так, что send_email по умолчанию обращается к send_mass_email

2022-05-22 12:29 UTC, dolamroth commented on starlette_web/contrib/sendgrid/email.py
> +        self.logger = logging.getLogger(__name__)
Готово

2022-05-22 15:18 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +        return self
если честно, я вообще не вижу смысла в нем как в контекстом менеджере. емейл-менеджер мы сами пишем. так зачем тогда усложнять? я бы не усложнял заранее

2022-05-22 15:18 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +        raise NotImplementedError
пока нет в этом необходимости. я бы не усложнял заранее

2022-05-22 15:22 UTC, DmitryBurnaev requested changes

2022-05-22 15:22 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +        await self.send_mass_email(subject, html_content, [to_email], from_email=from_email)
может давай оставим один метод с несколькими получателями?

2022-05-22 15:22 UTC, DmitryBurnaev commented on starlette_web/common/email/email_manager.py
> +            await sender.send_email(subject, html_content, to_email, from_email=from_email)
тогда зачем 2 метода? это переусложняет код (кажется)

2022-05-22 18:40 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +        return self
Я за то, чтобы всегда использовать контекстные менеджеры там, где используется логика "открыть-закрыть".

И для пользователя это не очень большое усложнение, потому что он так или иначе либо определяет методы _open, _closed в нашем классе, либо использует чужой контекстный менеджер внутри send_email.

Я немного переделал BaseEmailSender и SendgridAPIEmailSender, посмотри плиз. Кажется, так наиболее правильно.

2022-05-22 18:41 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +        raise NotImplementedError
убрал send_mass_email, теперь send_email отвечает за его логику

2022-05-22 18:41 UTC, dolamroth commented on starlette_web/common/email/email_manager.py
> +            await sender.send_email(subject, html_content, to_email, from_email=from_email)
убрал send_mass_email, теперь send_email отвечает за его логику

2022-05-23 17:25 UTC, DmitryBurnaev requested changes

2022-05-23 17:25 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +            await self._close()
а что мы закрываем, если упали при открытии? это должен разрулить наследник?

2022-05-23 17:25 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +            raise EmailSenderError(message=message, details=details)
ты уверен что рейз ошибки при выходе из контекстного менеджера - это хорошая идея. в нормальном мире как раз выход из контекста может быть по причине рейза ошибки. а тут еще и ты свою рейзишь. я бы так не делал, если честно

2022-05-23 17:25 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +        from_email: Optional[str] = None,
думаю что "from_email" должен быть обязательным аргументом. пусть клиент провайдит дефолт, которые он считает правильным

2022-05-23 17:25 UTC, DmitryBurnaev commented on starlette_web/common/http/exceptions.py
> -    request_url = ""
хм. а зачем мы это удаляем? это ошибка отправки данных "куда-то". по идее реквест урл это и есть "куда"

2022-05-23 17:25 UTC, DmitryBurnaev commented on starlette_web/contrib/sendgrid/email.py
> +                "email": settings.EMAIL_FROM,
тогда наверно лучше брать из аргумента "from_email"

2022-05-23 17:40 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +            await self._close()
Такая же логика есть в Django и в Selenium. Суть в том, что метод _open может открывать несколько разных "объектов". 

Вот пример из httpx
https://github.com/encode/httpx/blob/master/httpx/_client.py#L1983
https://github.com/encode/httpx/blob/master/httpx/_client.py#L1961

Метод `__enter__` открывает сначала транспорт, потом прокси. Допустим, у тебя упало открытие прокси. Тогда нужно закрыть транспорт.

В селениуме при открытии браузера вначале открывается Webdriver (отдельным процессом). Если просто закрыть браузер после ошибки, то процесс Webdriver останется висеть. Поэтому общий метод _close должен закрывать всё.

В таких утилитах всегда пишут close методы так, что они корректно отрабатывают, если объект УЖЕ закрыт.

2022-05-23 17:44 UTC, dolamroth commented on starlette_web/contrib/sendgrid/email.py
> +                "email": settings.EMAIL_FROM,
Согласен, тут упустил. Сейчас поправлю

2022-05-23 17:45 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +            return False
Я делаю re-raise, чтобы не увеличивать traceback на +1. В принципе, эту ветку можно убрать.

2022-05-23 18:04 UTC, dolamroth commented on starlette_web/common/email/base_sender.py
> +        from_email: Optional[str] = None,
Не уверен. Из этих параметров это единственный, который обычно не меняется.

2022-05-24 07:07 UTC, DmitryBurnaev approved these changes

2022-05-24 07:07 UTC, DmitryBurnaev commented on starlette_web/common/email/base_sender.py
> +            await self._close()
согласен)

2022-05-24 07:07 UTC, merged