[#11] Add lazy settings
DmitryBurnaev/starlette-web pull request #34
Opened 2022-08-19 14:37 UTC by dolamroth

2022-08-19 16:28 UTC, DmitryBurnaev requested changes
Круто!

2022-08-19 16:28 UTC, DmitryBurnaev commented on starlette_web/common/conf/__init__.py
> +        _getattr(self, "_user_settings")[key.upper()] = value
setattr?

2022-08-19 16:28 UTC, DmitryBurnaev commented on starlette_web/common/conf/__init__.py
> +            return _getattr(self, "_user_settings")[key]
Сможем избежать 2х getattr-ов?

2022-08-20 12:57 UTC, dolamroth commented on starlette_web/common/conf/__init__.py
> +        _getattr(self, "_user_settings")[key.upper()] = value
Тут сначала получаем объект _user_settings по ссылке из self (_getattr), а потом вызываем его метод __setitem__

2022-08-20 13:12 UTC, dolamroth commented on starlette_web/common/conf/__init__.py
> +            return _getattr(self, "_user_settings")[key]
Готово

2022-08-20 13:36 UTC, DmitryBurnaev approved these changes

2022-08-20 13:37 UTC, merged