Management commands
DmitryBurnaev/starlette-web pull request #4
Opened 2022-04-25 20:48 UTC by dolamroth

2022-04-26 06:47 UTC, DmitryBurnaev requested changes

2022-04-26 06:47 UTC, DmitryBurnaev commented on command.py
> +    if len(sys.argv) < 2:
сможем использовать [argparser](https://docs.python.org/3/library/argparse.html) ?

2022-04-26 06:47 UTC, DmitryBurnaev commented on starlette_web/common/management/base.py
> +    pass
есть модуль `common/exceptions.py` давай туда перенесем?

2022-04-26 06:47 UTC, DmitryBurnaev commented on starlette_web/common/management/base.py
> +            'Command',
можешь привести примеры для публичных методов? 
- не оч понятно как это работает
- кажется, это упадет, если `*/*/management/commands/*.py` будет лежать в другой директории

2022-04-26 06:47 UTC, DmitryBurnaev commented on starlette_web/common/management/base.py
> +            assert is_instance, f"Command must be inherited from common.management.base.BaseCommand"
сможем кидать `RuntimeError` или `TypeError`? (assert вне тестов лучше не использовать)

2022-04-26 06:47 UTC, DmitryBurnaev commented on starlette_web/common/utils.py
> +        raise ImportError('Module "%s" does not define a "%s" attribute/class' % (module_path, class_name)) from err
приведи плиз длину строки к 100 символам
или можешь заюзать 
```bash
sourve venv/bin/activate
make format
```

2022-04-26 06:47 UTC, DmitryBurnaev commented on starlette_web/tests/management/commands/test_parser.py
> +        print(options['accumulate'](options['integers']))
а эти команды, они нужны для ручного тестирования команд?

2022-04-26 08:04 UTC, dolamroth commented on command.py
> +    if len(sys.argv) < 2:
На этом этапе ещё нет, т.к. argparser ожидает заранее заданный набор параметров, а здесь он неизвестен.
argparser создается при инстанцировании команды, команда уже знает нужный набор параметров.

Вообще, все это очень близкая копия джанговского создания команд.

2022-04-26 08:06 UTC, dolamroth commented on starlette_web/common/management/base.py
> +    pass
Явно не в этом пулл-реквесте.

У меня идея сначала разгрести BaseHttpEndpoint, вынеся всё связанное с ним в сабмодуль common.http
Затем разгрести сентри и редис, вынеся их в контрибы

А уже потом уже классифицировать набор исключений и думать, можно ли их объединить в одно место или нет.
Но скорее всего не получится.

2022-04-26 08:09 UTC, dolamroth commented on starlette_web/common/management/base.py
> +            'Command',
Примеры: в корне проекта выполнить

```
python command.py test_parser 1 2 3 4 5 --sum
python command.py test_db
```

`*/*/management/commands/*.py` всегда резолвится от корневой директории, файлы ищутся только там.
Уровень импорта выше с кучей parent'ов соответствует тому же количеству директорий, что в шаблоне */*/management/commands/*.py (4 директории вглубь)

Не вижу ситуацию, при которой это может упасть.

2022-04-26 08:09 UTC, dolamroth commented on starlette_web/common/management/base.py
> +            assert is_instance, f"Command must be inherited from common.management.base.BaseCommand"
Буду кидать сразу CommandError

2022-04-26 08:10 UTC, dolamroth commented on starlette_web/tests/management/commands/test_parser.py
> +        print(options['accumulate'](options['integers']))
Да, плюс это пример как писать новые команды

2022-04-26 18:35 UTC, dolamroth commented on starlette_web/common/management/base.py
> +            'Command',
Добавил ещё одну команду, которая вызывает `call_command`

2022-04-27 14:34 UTC, DmitryBurnaev commented on starlette_web/common/management/base.py
> +    pass
хорошая идея) давай так пока оставим

2022-04-27 14:38 UTC, DmitryBurnaev approved these changes

2022-04-27 14:39 UTC, merged