Constance with database backend
DmitryBurnaev/starlette-web pull request #43
Opened 2022-10-09 18:11 UTC by dolamroth

2022-10-09 19:28 UTC, DmitryBurnaev requested changes

2022-10-09 19:28 UTC, DmitryBurnaev commented on starlette_web/contrib/constance/__init__.py
> +                raise NotSupportedError
```suggestion
                raise NotSupportedError(
                    f"Key {key} is not supported for configured constance"
                )
```

ну и везде ниже, можешь тоже плиз запроввадить такое сообщение или подобное (думаю было бы круто в ошибке видеть какой именно key не найден)

2022-10-09 19:28 UTC, DmitryBurnaev commented on starlette_web/contrib/constance/__init__.py
> +            raise NotSupportedError
```suggestion
            raise NotSupportedError(
                f"Key {key} is not supported for configured constance"
            )
```

2022-10-09 19:28 UTC, DmitryBurnaev commented on starlette_web/contrib/constance/__init__.py
> +        expected_type = settings.CONSTANCE_CONFIG[key][2]
довольно тяжело по коду понять что именно должно быть в `settings.CONSTANCE_CONFIG`
мы можем документации / докстринге привести прям пример?

плюс именно тут при IndexError думаю тяжеловато разобраться что именно не так сконфигурено.

2022-10-09 19:28 UTC, DmitryBurnaev commented on starlette_web/tests/conftest.py
> +        "TEST_CONSTANT_DATETIME": (datetime.now(), "Test constant datetime", datetime),
а есть смысл от такого дефолта ?  так понимаю `datetime.now()` - это дефолт?  понимаю что это по сути для теста, но просто получается, что если так в settings сконфигурить, то  значение  - всегда будет одинаковое (по сути время старта воркера), может имеется ввиду что-то типа callable? `datetime.now` ну и `uuid.uuid4` соответственно?

2022-10-09 21:34 UTC, dolamroth commented on starlette_web/contrib/constance/__init__.py
> +                raise NotSupportedError
добавил, только сообщение чуть другое

2022-10-09 21:34 UTC, dolamroth commented on starlette_web/contrib/constance/__init__.py
> +            raise NotSupportedError
добавил, только сообщение чуть другое

2022-10-09 21:35 UTC, dolamroth commented on starlette_web/tests/conftest.py
> +        "TEST_CONSTANT_DATETIME": (datetime.now(), "Test constant datetime", datetime),
сделал статические дефолты

динамические значения, вообще говоря, не предусматриваются (по крайней мере в django-constance так)

2022-10-09 21:36 UTC, dolamroth commented on starlette_web/contrib/constance/__init__.py
> +        expected_type = settings.CONSTANCE_CONFIG[key][2]
добавил пример в документацию, а также todo на реализацию системы по типу django.checks

2022-10-10 07:19 UTC, DmitryBurnaev approved these changes

2022-10-10 07:19 UTC, merged