WIP: Fixes #50: Check library for compatability with anyio model
DmitryBurnaev/starlette-web pull request #74
Opened 2023-02-18 14:40 UTC by dolamroth

- Removed deprecated util for spawning orphan tasks
- Run Websocket handler in enclosed TaskGroup and CancelScope
- Set fixed duration for redis lock to be released

2023-02-19 10:27 UTC, DmitryBurnaev requested changes

2023-02-19 10:27 UTC, DmitryBurnaev commented on starlette_web/common/ws/base_endpoint.py
> +import anyio
добавь плиз его  в `setup.cfg`

2023-02-19 10:27 UTC, DmitryBurnaev commented on starlette_web/common/ws/base_endpoint.py
> +    permission_classes: ClassVar[List[Union[Type[BasePermission], OperandHolder]]] = []
а у тебя py3.10+? если так, то как думаешь на счет такой вариации тайп-хинтинга?
```suggestion
    permission_classes: ClassVar[list[Type[BasePermission] | OperandHolder]] = []
```

2023-02-19 10:27 UTC, DmitryBurnaev commented on starlette_web/common/ws/base_endpoint.py
>      background_task: asyncio.Task
а теперь вместо бекраунд таски - будет таск-группа?

2023-02-19 10:27 UTC, DmitryBurnaev commented on starlette_web/common/ws/base_endpoint.py
> +        )
получается что бы сделать наследника, которому нужно именно бекраунд-таска, я обязан буду реализовать этот метод (и оставить видимо его просто пустым)

2023-02-19 10:38 UTC, dolamroth commented on starlette_web/common/ws/base_endpoint.py
> +import anyio
anyio вообще идёт в зависимостях к starlette, думаешь, стоит отдельно добавить?

2023-02-19 10:40 UTC, dolamroth commented on starlette_web/common/ws/base_endpoint.py
> +    permission_classes: ClassVar[List[Union[Type[BasePermission], OperandHolder]]] = []
отложил до https://github.com/DmitryBurnaev/starlette-web/issues/25 )))
вообще, я себе поставил новый pycharm, но питон у меня пока 3.9.5

2023-02-19 10:48 UTC, dolamroth commented on starlette_web/common/ws/base_endpoint.py
>      background_task: asyncio.Task
действительно, эту аннотацию забыл убрать

раньше была теоретическая уязвимость в архитектуре, если несколько раз срабатывал метод on_receive, то значение self.background_task перезаписывалось, а отменялась в self.on_disconnect только последняя. Здесь отмена происходит за счёт cancelscope из anyio, который должен сам отменить всё

2023-02-19 10:52 UTC, dolamroth commented on starlette_web/common/ws/base_endpoint.py
> +        )
наверное, наоборот

для бэкграунд таски в методе будет бесконечный цикл
а для однократного действия - просто какой-то процедурный код, или пустой метод, если действие не требуется

2023-02-19 22:14 UTC, dolamroth commented on starlette_web/common/ws/base_endpoint.py
> +import anyio
Добавил anyio + websockets

2023-02-20 06:58 UTC, DmitryBurnaev commented on starlette_web/common/ws/base_endpoint.py
> +    permission_classes: ClassVar[List[Union[Type[BasePermission], OperandHolder]]] = []
ок) пусть будет пока с поддержкой 3.9) я не против))

2023-02-20 07:00 UTC, DmitryBurnaev approved these changes

2023-02-20 07:01 UTC, DmitryBurnaev commented on starlette_web/common/ws/base_endpoint.py
>      background_task: asyncio.Task
да. я заметил) спасибо, что подправил!

2023-02-20 07:01 UTC, merged