JSON utilities (custom encoder, contrib.camel_case)
DmitryBurnaev/starlette-web pull request #8
Opened 2022-05-02 13:13 UTC by dolamroth

2022-05-02 13:27 UTC, DmitryBurnaev requested changes

2022-05-02 13:27 UTC, DmitryBurnaev commented on starlette_web/common/utils/json.py
> +def duration_iso_string(duration):
давай к тулзам (и публичным для модуля методам) писать докстригни поясняющие как метод работает (желательно с примерами)

2022-05-02 13:27 UTC, DmitryBurnaev commented on starlette_web/contrib/camel_case/utils.py
> +        return False
нужны тесты

2022-05-02 15:52 UTC, dolamroth commented on starlette_web/common/utils/json.py
> +def duration_iso_string(duration):
Добавил

2022-05-02 15:52 UTC, dolamroth commented on starlette_web/contrib/camel_case/utils.py
> +        return False
Добавил

2022-05-03 11:10 UTC, DmitryBurnaev requested changes

2022-05-03 11:10 UTC, DmitryBurnaev commented on starlette_web/contrib/camel_case/utils.py
> +def underscoreize(data, **options):
- typehints
- примеры с конвертом итерируемых данных
- можно options заменить просто на kwarg ignore_fields
- можно оформить доктесты (тесты и примеры в одном флаконе будут)

2022-05-03 11:10 UTC, DmitryBurnaev commented on starlette_web/tests/contrib/test_camel_case.py
> +    result = OrderedDict([
почему в тесте результат именно OrderedDict? метод (насколько понял по коду) возаращет просто словарь

2022-05-03 11:10 UTC, DmitryBurnaev commented on starlette_web/tests/contrib/test_camel_case.py
> +
нужны тесты на конверт списка (опять же в теории можно через доктесты сделать)

2022-05-03 11:10 UTC, DmitryBurnaev commented on starlette_web/tests/utils/test_json.py
> +    )
в либе есть (в setup.cfg в разделе develop) black-форматтер. плиз юзай его перед формированием PR-ов

2022-05-03 11:10 UTC, DmitryBurnaev commented on starlette_web/tests/utils/test_json.py
> +    )
есть make-команда

1. активируешь вирт. окружение
2. `make format`

2022-05-03 12:10 UTC, dolamroth commented on starlette_web/tests/utils/test_json.py
> +    )
Не понял, а что здесь не так?

Я не люблю автоматические форматтеры, потому что они пытаются поправить код не так, как мне надо. Например, после переноса строки делают 2 отступа вместо 1 в таких случаях

```
class A:
    def __init__(
        self,
        param_1,
        param_2,
    )
```

2022-05-03 12:22 UTC, dolamroth commented on starlette_web/contrib/camel_case/utils.py
> +def underscoreize(data, **options):
- Тайпхинты добавил
- Примеры есть в докстринге
- Параметры из options прописал явно
- Лучше не надо, тесты пусть отдельно будут

2022-05-03 12:23 UTC, dolamroth commented on starlette_web/tests/contrib/test_camel_case.py
> +    result = OrderedDict([
Так работает [либа](https://github.com/vbabiy/djangorestframework-camel-case) 
Не вижу смысла менять

2022-05-03 12:23 UTC, dolamroth commented on starlette_web/tests/contrib/test_camel_case.py
> +
Добавил

2022-05-03 12:39 UTC, dolamroth commented on starlette_web/tests/utils/test_json.py
> +    )
Отформатировал с black8

2022-05-03 14:23 UTC, DmitryBurnaev requested changes

2022-05-03 14:23 UTC, DmitryBurnaev commented on starlette_web/contrib/camel_case/utils.py
> +def camelize(data: JSONType, ignore_fields=()) -> JSONType:
давай задавать для всех параметров публичных методов тип в тайпхинтах?

2022-05-03 14:23 UTC, DmitryBurnaev commented on starlette_web/contrib/camel_case/utils.py
> +        new_dict = OrderedDict()
зачем нам тут OrderedDict? python c версии 3.6 в обычном дикте сохраняет последовательность ключей
при том, ты тут нарушаешь соглашение по типу: говоришь что вернешь JSONType, а возвращаешь OrderedDict (которого нет в перечисленных json- типах)

2022-05-03 14:34 UTC, dolamroth commented on starlette_web/tests/utils/test_json.py
> +    )
Итоговый результат выглядит не так, как у тебя

Я же делаю json.dumps без indent

2022-05-03 16:06 UTC, DmitryBurnaev approved these changes

2022-05-03 16:06 UTC, merged