Fixes #76: Use redis-like pattern for BaseCache.async_keys
DmitryBurnaev/starlette-web pull request #90
Opened 2023-02-26 22:09 UTC by dolamroth

2023-02-28 05:15 UTC, DmitryBurnaev requested changes

2023-02-28 05:15 UTC, DmitryBurnaev commented on starlette_web/common/utils/regex.py
> +def redis_pattern_to_re_pattern(pattern: str) -> re.Pattern:
можешь плиз добавить доксктрингу с 1-2 примерами и описаниями что примерно делает эта функция

2023-02-28 05:15 UTC, DmitryBurnaev commented on starlette_web/contrib/redis/cache.py
> +            px=int(timeout * 1000) if timeout is not None else None,
подскажи плиз: зачем перешли с ex на px? если не сложно - укажи в докстринге, что timeout в мс (это ведь так?)

2023-02-28 05:15 UTC, DmitryBurnaev commented on starlette_web/tests/utils/test_redis_pattern_matcher.py
> +        _ = redis_pattern_to_re_pattern("keys:[[*]]")
подскажи еще плиз: зачем ты присваиваешь значение из возвращаемой функции к заведомо неиспользуемой переменной?

2023-02-28 06:12 UTC, dolamroth commented on starlette_web/contrib/redis/cache.py
> +            px=int(timeout * 1000) if timeout is not None else None,
Не, таймаут так и остался в секундах.
Суть в том, что EX принимает значения в целых секундах, а PX - в целых миллисекундах. PX нужен, чтобы иметь возможность передавать дробные значения в секундах (как было в aioredis).

2023-02-28 06:31 UTC, dolamroth commented on starlette_web/tests/utils/test_redis_pattern_matcher.py
> +        _ = redis_pattern_to_re_pattern("keys:[[*]]")
Мне кажется, это привычка навеяна паскалем))
Где есть процедуры (не возвращающие значения) и функции (возвращающие)

Убрал присваивание

2023-02-28 06:31 UTC, dolamroth commented on starlette_web/common/utils/regex.py
> +def redis_pattern_to_re_pattern(pattern: str) -> re.Pattern:
Добавил

2023-03-01 05:55 UTC, DmitryBurnaev approved these changes

2023-03-01 05:56 UTC, merged

2023-03-01 05:56 UTC, DmitryBurnaev commented on starlette_web/tests/utils/test_redis_pattern_matcher.py
> +        _ = redis_pattern_to_re_pattern("keys:[[*]]")
ох. аж олдскулы не свело))