WIP: Refs #67: contrib.scheduler with posix crontab support
DmitryBurnaev/starlette-web pull request #99
Opened 2023-03-02 21:40 UTC by dolamroth

2023-03-05 17:27 UTC, DmitryBurnaev requested changes

2023-03-05 17:27 UTC, DmitryBurnaev commented on docs/receipts/scheduler.md
> +```python
```suggestion
```bash
```

2023-03-05 17:27 UTC, DmitryBurnaev commented on setup.cfg
> +    py_win_task_scheduler; sys_platform == 'win32'
1) при установке в unix-like систему, как себя ведет либа?
2) можем запинить ее версию?

2023-03-05 17:27 UTC, DmitryBurnaev commented on starlette_web/common/conf/__init__.py
> +        _getattr(self, "_user_settings")["STARLETTE_SETTINGS_MODULE"] = settings_module
а тут точно не `_setattr`  нужен?

2023-03-05 17:27 UTC, DmitryBurnaev commented on starlette_web/contrib/scheduler/apps.py
> +                _ = json.JSONEncoder(sort_keys=True).encode(job)
```suggestion
                json.JSONEncoder(sort_keys=True).encode(job)
```

2023-03-05 17:27 UTC, DmitryBurnaev commented on starlette_web/contrib/scheduler/apps.py
> +                    _ = next(croniter.croniter(job[0]))
```suggestion
                    next(croniter.croniter(job[0]))
```
\+ добавь тут плиз коммент почему именно мы должны вызывать next и что за магия творится) буквально в 2-3х словах

2023-03-05 17:27 UTC, DmitryBurnaev commented on starlette_web/contrib/scheduler/backends/base.py
> +        job = self._get_job_by_hash(job_hash)
можно попросить тут сделать распаковку параметров? а-ля:
```python
something, handler_name, param2, param3 = self._get_job_by_hash(job_hash)
```

либо еще лучше сделать именованный namedtuple

```python

class JobParams(NamedTuple):
    handler_name: str
    param1: int
    ....

job_params =  JobParams(*self._get_job_by_hash(job_hash))

print(job_params.handler_name)

```

как думаешь, получится тут так?

2023-03-05 17:27 UTC, DmitryBurnaev commented on starlette_web/contrib/scheduler/backends/posix.py
> +        os.system("%s %s" % (self.settings.CRONTAB_EXECUTABLE, path))
правильно я тебя понял, что через наш кронтаб можно будет запустить что угодно (ну то есть то, что можно запустить через CRONTAB_EXECUTABLE?)
есть пара вопросов:
1) от имени какого юзера будет выполняться ?
2) на сколько этот подход безопасен (пока не придумал вектор атаки, но есть переживания в этом плане)
3) можем не использовать старый стиль форматирования?
```suggestion
        os.system(f"{self.settings.CRONTAB_EXECUTABLE} {path}")
```

2023-03-05 17:37 UTC, dolamroth commented on setup.cfg
> +    py_win_task_scheduler; sys_platform == 'win32'
Собственно, я в кронтаб файл включил установку scheduler для тестов. Эта зависимость не будет установлена.

Насчёт версии не уверен, я не разобрался как скачивать прям с гита (pip требует консольного гита), а сделал просто скачивание архива репозитория py_win_task_scheduler с мастер-ветки. Там версионирования, соответственно, нет.

2023-03-05 17:45 UTC, dolamroth commented on starlette_web/contrib/scheduler/backends/posix.py
> +        os.system("%s %s" % (self.settings.CRONTAB_EXECUTABLE, path))
Не совсем, кронтаб всегда запускает команду

```
cd PROJECT_ROOT && sys.executable command.py scheduler --cmd=run --jobhash=...
```

Реализация для крона вообще почти 1-в-1 взята отсюда https://github.com/kraiz/django-crontab/tree/master/django_crontab
А для винды -- адаптирована под django_crontab

Соответственно,
1) добавление записей в кронтаб производится под виртуальным окружением проекта и от того же пользователя, у кого развернут проект и выполняться будет от того же пользователя / на винде я сделал опциональные параметры username / password, т.к. может не быть админских прав для добавления таски, а по умолчанию от SYSTEM

2) зависит от команды, которую юзер напишет, имхо

3) поправлю позже, просто я пару раз садился за переписывание django-crontab, потом психовал и откатывал как у них, поэтому под конец уже ничего не стал менять

2023-03-05 17:48 UTC, dolamroth commented on starlette_web/contrib/scheduler/apps.py
> +                    _ = next(croniter.croniter(job[0]))
Либа croniter генерирует генератор :) который бесконечно возвращает время следующего запуска таски по переданному шаблону. Здесь я просто дергаю генерацию 1 раз, чтобы посмотреть, упадет ли с ошибкой (из-за невалидного паттерна кронтаба) или нет

Например, от "* * * * 8" упадет, сказав, что значение для дня недели невалидное

2023-03-05 17:50 UTC, dolamroth commented on starlette_web/common/conf/__init__.py
> +        _getattr(self, "_user_settings")["STARLETTE_SETTINGS_MODULE"] = settings_module
Тут всё норм, смотри метод `__setattr__`

Сначала получаем внутренний атрибут инстанса, а уже у него вызываем `__setitem__`

2023-03-05 18:01 UTC, dolamroth commented on starlette_web/contrib/scheduler/backends/base.py
> +        job = self._get_job_by_hash(job_hash)
Насчёт NamedTuple вряд ли, т.к. я делаю JSONEncoder(...).encode(job) для получения хеша

А распаковку сделаю

2023-03-07 06:02 UTC, DmitryBurnaev requested changes

2023-03-07 06:02 UTC, DmitryBurnaev commented on setup.cfg
> +    py_win_task_scheduler; sys_platform == 'win32'
да. ок) пускай так будет

2023-03-07 06:19 UTC, dolamroth commented on starlette_web/contrib/scheduler/backends/posix.py
> +    def add_jobs(self):
На Posix update_job сначала удаляет все jobs проекта (по хешу), а затем передобавляет все. (см. update_jobs в базовом классе)

На винде переопределил update_jobs, т.к. там процесс удаления/добавления посложнее

2023-03-07 06:22 UTC, dolamroth commented on starlette_web/contrib/scheduler/backends/base.py
> +                tempfile.gettempdir(), self._get_project_level_hash() + ".lock"
Да, это баг, причём я как раз вчера перед сном про него вспомнил. Но ты увидел раньше, чем я поправил))

2023-03-07 06:28 UTC, dolamroth commented on starlette_web/contrib/scheduler/apps.py
> +                    _ = next(croniter.croniter(job[0]))
готово

2023-03-07 06:28 UTC, dolamroth commented on starlette_web/contrib/scheduler/management/commands/scheduler.py
> +            "--cmd", choices=["add", "show", "remove", "run"], type=str, required=True
готово

2023-03-07 06:57 UTC, DmitryBurnaev approved these changes

2023-03-07 06:57 UTC, DmitryBurnaev commented on starlette_web/contrib/scheduler/backends/posix.py
> +    def add_jobs(self):
ok. спасибо) значит я ошибся.

2023-03-07 06:58 UTC, merged